name: Unit tests (BrowserStack)

on: [push]

jobs:
  full_test_run:
    strategy:
      fail-fast: false
      matrix:
        browser: [Chrome, ChromeLast, Edge, EdgeLast, Firefox, FirefoxLast, Safari, iOS15, Android]

    env:
      USE_BROWSER_STACK: true

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Bootstrap packages
      run: npm run bootstrap

    - name: Build packages
      run: npm run build

    - name: Unit tests
      env:
        BROWSER: ${{ matrix.browser }}
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
        BROWSER_STACK_BUILD_NAME: ${{ format('{0} / {1} / {2}', github.ref, github.run_id, matrix.browser) }}
      run: npm run test:ci