name: Unit tests

on: [push]

jobs:
  full_test_run:

    env:
      USE_BROWSER_STACK: true

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Bootstrap packages
      run: npm run bootstrap

    - name: Build packages
      run: npm run build

    - name: Wait for BrowserStack ready
      uses: mydea/action-wait-for-api@v1
      with:
        url: "https://api.browserstack.com/automate/plan.json"
        headers: '{"Authorization": "Basic " + Buffer.from(${{ secrets.BROWSER_STACK_USERNAME }} + ':' + ${{ secrets.BROWSER_STACK_ACCESS_KEY }}).toString('base64')}'
        expected-response-field: "parallel_sessions_running"
        expected-response-field-value: "0"
        interval: "80"
        timeout: "120"

    - name: Unit tests
      env:
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
        BROWSER_STACK_BUILD_NAME: ${{ format('{0} / {1}', github.ref, github.run_id) }}
      run: npm run test:ci